package-lock.json, package.json, src/App.tsx, src/assets/videos/videos.ts, src/common/constants/constants.ts, src/common/constants/enums.ts, src/common/interfaces/IVideoCard.ts, src/common/utils/utils.ts, src/components/atoms/buttons/PrimaryButton.tsx, src/components/atoms/headers/Header.tsx, src/components/atoms/video/Video.tsx, src/components/atoms/videoInfo/VideoInfo.tsx, src/components/atoms/videoTitle/VideoTitle.tsx, src/components/molecules/videoCard/VideoCard.tsx, src/components/organisms/VideoList.tsx, src/components/templates/NavBar.tsx
Inital Work on `VideoCard`. Also added some required dependencies
=> Create Video Card

.prettierrc, config-overrides.js, src/App.test.tsx, src/App.tsx, src/assets/videos/videos.ts, src/common/constants/constants.ts, src/common/constants/enums.ts, src/common/interfaces/IVideoCard.ts, src/common/utils/reactUtils.ts, src/common/utils/utils.ts, src/components/atoms/buttons/PrimaryButton.tsx, src/components/atoms/headers/Header.tsx, src/components/atoms/pageTitle/PageTitle.tsx, src/components/atoms/video/Video.tsx, src/components/atoms/videoInfo/VideoInfo.tsx, src/components/atoms/videoTitle/VideoTitle.tsx, src/components/molecules/NavList.tsx, src/components/molecules/videoCard/VideoCard.tsx, src/components/organisms/videoList/VideoList.tsx, src/components/templates/AnimationPage.tsx, src/components/templates/Contact.tsx, src/components/templates/Home.tsx, src/components/templates/NavBar.tsx, src/components/templates/SeriesPage.tsx, src/components/templates/VideoList.tsx, src/components/templates/VideoListPage.tsx, src/index.tsx, src/reportWebVitals.ts, src/setupTests.ts, tsconfig.json
=> Add and run prettier

src/App.tsx, src/components/atoms/linkForEnum/LinkForEnum.tsx, src/components/atoms/pageTitle/PageTitle.tsx, src/components/atoms/videoInfo/VideoInfo.tsx, src/components/atoms/videoInfoWithLink/videoInfoWithLink.tsx, src/components/atoms/videoTitle/VideoTitle.tsx, src/theme.tsx
=> Initial Theme provider stuff

package-lock.json, package.json, src/App.tsx, src/common/constants/enums.ts, src/components/atoms/headers/Header.tsx, src/components/footers/Footer.tsx, src/components/molecules/footers/BottomIcons.tsx, src/components/molecules/footers/FooterLinks.tsx, src/components/organisms/Footer/Footer.tsx, src/index.tsx, src/theme.tsx
=> Starting on Footer

src/App.tsx, src/common/utils/enumColorUtils.ts, src/components/atoms/chipsForEnum/ChipsForEnum.tsx, src/components/atoms/videoInfoWithLink/videoInfoWithLink.tsx, src/components/molecules/videoCard/VideoCard.tsx, src/components/templates/VideoListPage.tsx
=> Chips (tags) on VideoCards

package-lock.json, package.json, src/assets/videos/videos.ts, src/components/atoms/chipsForEnum/ChipsForEnum.tsx, src/components/atoms/video/Video.tsx
Discovered `ReactPlayer` to play various URLs. 
Implemented here. 
You can see a test YouTube render below:
=> utilizing ReactPlayer to render Videos

.vscode/settings.json, src/App.tsx, src/components/molecules/About/AboutPage.tsx, src/components/molecules/contactForm/ContactForm.tsx, src/components/templates/About.tsx, src/components/templates/ErrorBoundary.tsx
Our nav bar is broken, so I've added an error handler to deal with that in the future. I think I remember this being fixed in another PR, but if not I can deal with that.
Also added vscode setting to automatically remove unused imports.
=> Some route fixing

src/common/utils/newStyle.ts, src/components/molecules/footer/BottomIcons.tsx, src/components/organisms/Footer/Footer.tsx
=> Fixed Footer coloring

src/assets/pages/directorProducer.ts, src/assets/pages/recentWork.ts, src/assets/videos/adHocVideos.ts, src/components/atoms/chipsForEnum/ChipsForEnum.tsx
Vika's added gover effects to the Chips. Here ya go.
Closes #98
=> Add hover effect

src/components/molecules/seriesListCard/SeriesListCard.tsx
=> Remove series tags on series page

src/components/molecules/footer/FooterLinks.tsx
=> Footer Link adjustments

src/assets/socialLinks/SocialLinks.ts
=> Added social media links

src/components/molecules/videoCard/VideoCard.tsx
Implemented this just in case we _do_ want to run with it.
=> "Play" Arrow on VideoCards

src/components/atoms/buttons/ModalCloseButton.tsx, src/components/organisms/modal/VideoModal.tsx
Any background color on the `X`?
=> `X` ModalCloseButton on Modal

src/components/atoms/formInput/FieldError.tsx, src/components/atoms/pageTitle/PageTitle.tsx, src/components/molecules/contactForm/ContactForm.tsx, src/theme.tsx
Quick fix for #121 
Happy to make things better, but here's something to show Kurt tomorrow.
=> Quick fix for errors

src/components/atoms/formInput/TextInput.tsx, src/components/atoms/pageTitle/PageTitle.tsx, src/components/atoms/videoInfo/VideoInfo.tsx, src/components/atoms/videoTitle/VideoTitle.tsx, src/components/molecules/About/AboutPage.tsx, src/components/molecules/contactForm/ContactForm.tsx, src/index.css, src/theme.tsx
=> h1, h3, body 2 styling updates

src/components/atoms/buttons/HireMeButton.tsx, src/components/atoms/buttons/ShowMoreButton.tsx, src/components/organisms/videoList/VideoList.tsx
=> Button Styling Update

src/components/atoms/pageTitle/PageTitle.tsx
=> 8px added between title and underline

src/components/organisms/videoList/VideoList.tsx, src/theme.tsx
Buttons centered and gap shrunk:
=> Fixing Button Layout

src/components/atoms/pageTitle/PageTitle.tsx, src/components/atoms/videoInfo/VideoInfo.tsx, src/components/molecules/About/AboutPage.tsx, src/components/molecules/contactForm/ContactForm.tsx, src/components/molecules/seriesVideoCard/SeriesVideoCard.tsx, src/components/pages/kurtApp/KurtApp.tsx, src/components/templates/NavBar.tsx, src/index.css, src/theme.tsx
=> Several UI updates

src/components/molecules/footer/BottomIcons.tsx, src/components/molecules/footer/FooterLinks.tsx, src/components/organisms/Footer/Footer.tsx, src/theme.tsx
Updates to the footer links.
#206
=> Updated Footer Icons

src/components/molecules/seriesDetaillDescription/SeriesDetailDescription.tsx, src/components/templates/SeriesDetailPage.tsx
=> Updated image behavior

src/components/molecules/footer/FooterLinks.tsx, src/components/organisms/Footer/Footer.tsx
=> Wrapped Link around Typography

src/components/molecules/footer/FooterLinks.tsx
=> Changed flex from 'space-between' to 'flex-start'

src/components/templates/About.tsx
Closes #223 
About Page Contact Form
=> extra paddig removed

src/components/organisms/seriesDetailEpisodes/SeriesDetailEpisodes.tsx, src/components/organisms/videoList/VideoList.tsx
Closes #224 and #225
For #224 
32px paddingBottom added:
=> bottom padding added

src/assets/pages/recentWork.ts, src/common/constants/enums.ts, src/components/molecules/About/AboutPage.tsx, src/components/templates/Home.tsx
=> Update styling a bit and made page link

src/components/atoms/buttons/OutlinedButton.tsx, src/components/molecules/contactForm/ContactForm.tsx
turns out, we don't want care about making our env's secret for this, nor can we. What a fun change. 
@mwilkins74 and @ChuckBTaylor if you're looking for the variables to work on this form for any reason (style, etc.) they are located in our [emailjs](https://www.emailjs.com/) account. Or we can hard code or decide to make them an env file if we want.
=> Form working like it did a year ago
